### ISSUE TITLE
ARG order in Dockerfile

### ISSUE THREAD

**Issue by MichaelRSilva** [flaviostutz/ruller#10]
In the `Dockerfile` the `ARG MAXMIND_LICENSE_KEY` is declared before any `FROM` to be used globally, but the [documentation](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) says:

'An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage:'

For the `/sample/download-geolite2-city.sh` script to be able to use the `MAXMIND_LICENSE_KEY` argument, I had to add `ARG MAXMIND_LICENSE_KEY` after the `FROM golang:1.14.3-alpine3.11 AS BUILD` command.

```
# Global ARG (set before the first build-stage), can be used in each build-stage.
ARG MAXMIND_LICENSE_KEY

FROM golang:1.14.3-alpine3.11 AS BUILD

# Added
ARG MAXMIND_LICENSE_KEY

RUN apk add curl

WORKDIR /opt

# download db if arg is not empty
ADD /sample/download-geolite2-city.sh /opt/
RUN /opt/download-geolite2-city.sh $MAXMIND_LICENSE_KEY
```

What do you think we add this fix?

**Comment by flaviostutz** [comment]
All stages will get the same ARG value used on build command, right? If so, let's remove it as the first argument and keep it on the first stage.

**Comment by MichaelRSilva** [comment]
Yes, we can remove the first (global) and keep only the first stage.

**Comment by reinaldocomputer** [comment]
I think this issue is already solved and it can be closed.
@MichaelRSilva or @flaviostutz
