### ISSUE TITLE
Dynamic Rules

### ISSUE THREAD

**Issue by reinaldocomputer** [flaviostutz/ruller#15]
Hello guys,
I've been using the ruller in a project which the rules change every day. I think it would be nice if we didn't need to rebuild and deploy for each change.
I was thinking about add the rules in a database instead of files.
What do you guys think about these changes?

**Comment by flaviostutz** [comment]
Unfortunately this would break the whole scalability of ruller because it is based on code generation and compiling.

What are your thoughts about this?

**Comment by reinaldocomputer** [comment]
I understand that are many advantages in the current state like:
- Scalability
- High speed of access
- Auditing
But maybe we can find a way to turn it more dynamically in behalf of usability.
For example:
We can save the initial state on memory and allow changes in the data, it would allow us:
1 - Testing without deploy changes in the environment.
2- If something goes wrong and a endpoint get down, for example, we can get in and change it values to another valid point.

What do you think?

**Comment by flaviostutz** [comment]
I didn’t get it. What about code generation and compiling?

**Comment by reinaldocomputer** [comment]
The previous approach allow us to test and fix mistakes in run mode, but in the next step we need to change in the code and the modifications will get in in the next release. 
Or instead of memory we could use a REDIS and try to mix the two approaches.
What do you think?

**Comment by flaviostutz** [comment]
I still didn't get how you will handle the code changing while we are doing static code generation here for the rules.
Please explain in details.
