### ISSUE TITLE
Error building ruller-sample Docker image

### ISSUE THREAD

**Issue by werberson** [flaviostutz/ruller#2]
According to this [official post](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/), the download of the GeoLite2-City database is no longer being served from the public GeoLite2 page.

The following line on Dockerfile breaks the build.
https://github.com/flaviostutz/ruller/blob/b7a2e4802aca2bbcb584f1ce1d977d25d81fe766/Dockerfile#L3

**Comment by flaviostutz** [comment]
You are right. I even updated another Dockerfile because of this change. 
While we don’t update here, check the instructions at https://github.com/flaviostutz/ruller-sample-feature-flag/blob/master/Dockerfile

**Comment by werberson** [comment]
I have two suggestions.

1. Map a volume
This way, we don't need to care about the database on build time.
e.g. `docker run -v /local/GeoLite2-City.mmdb:/GeoLite2-City.mmdb`

2. Use MaxMind's permanent link and personal license key to continue downloading the database with cURL at image creation time.
e.g.
```Dockerfile
ARG MAXMIND_LICENSE_KEY
RUN curl https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz --output /opt/GeoLite2-City.tar.gz 
```

What approach do you prefer?

**Comment by flaviostutz** [comment]
The second approach is way better. MAXMIND_LICENSE_KEY will be an build
ARG, correct? It would be good to handle empty values so that it won't be
downloaded so that build won't have it.

**Comment by werberson** [comment]
yes, the argument is required to build the image.

**Comment by flaviostutz** [comment]
But if the argument is empty, the build must work, but without the database
embedded to the image, ok?

**Comment by werberson** [comment]
ok
