### ISSUE TITLE
Rearrange files structure

### ISSUE THREAD

**Issue by werberson** [flaviostutz/ruller#4]
I would like to suggest the following file organization. 

```sh
 ├──  BENCHMARK.md
 ├──  LICENSE
 ├──  README.md
 ├──  go.mod
 ├──  go.sum
 ├──  ruller.go
 └──  sample/
 │  ├────  Dockerfile
 │  ├────  docker-compose.yml
 │  ├────  go.mod
 │  ├────  go.sum
 │  ├────  main.go
 │  └────  startup.sh
```

1. Move the library source code to the root of the project
So we can import the library using `import "github.com/flaviostutz/ruller"` instead of `import "github.com/flaviostutz/ruller/ruller"`
2. Move all sample related files to the `sample` folder

Note: These changes may break non-go-modules projects using the ruller library.

**Comment by flaviostutz** [comment]
This would be great! But if you do this, remind to fix the other DSL
projects too.
