### ISSUE TITLE
Sample example

### ISSUE THREAD

**Issue by gutorc92** [flaviostutz/ruller#6]
The sample example project is not working due to wrong input variables.

**Comment by flaviostutz** [comment]
Which variables? Could you please paste the error?

**Comment by gutorc92** [comment]
@flaviostutz 

I run the sample project and try the post request of example and get this error:

![image](https://user-images.githubusercontent.com/2671806/84771793-5e55af00-afb0-11ea-99c8-865d6d0b0449.png)

I send the same example request on readme:

![image](https://user-images.githubusercontent.com/2671806/84771897-86451280-afb0-11ea-87b1-2329d5c9de92.png)

**Comment by flaviostutz** [comment]
Thanks! @gutorc92
